title: Estudio R
email: estudior17@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este sitio web fue creado utilizando Jekyll, el código fuente está disponible en Github.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username:  EstudioR

# Build settings
markdown: kramdown
